apiVersion: v2
name: sealed-secrets
version: 1.0.0
description: A Helm chart for sealed-secrets

dependencies:
- name: sealed-secrets
  version: ">=1.2.8"
  repository: "https://charts.bitnami.com/bitnami"
